# This file has been created automatically, do not change
# 
# This file has been generated by 'make_Co1_2A_involution.py'
# 
# It (hopefully) contains a representatives of all classes in G_x0 
# which map to class 2A in Co_1.
# 
# Note that this file uses functions from module 'involutions.c'.
# So when testing that module, it is useful to have such a transversal.
# But the tests for that module which use these representatives
# should be preceded by independent tests.
# 


Co1_class_2A_samples = [
"M<y_80fh>",
"M<y_80fh*d_1h>",
"M<y_80fh*d_3h>",
"M<y_80fh*d_801h>",
"M<y_80fh*d_803h>",
"M<y_0fh*x_1003h*d_5h>",
"M<y_100fh>",
]
