[build-system]
requires = [
   "setuptools", 
   "wheel", 
   "Cython", 
   "numpy", 
   "scipy", 
   "regex", 
   "pytest"
]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
environment = "pip-global-option=\"build_ext --inplace\""
skip = "*-win32 *-manylinux_i686 cp36-* cp311-* pp*"
build-verbosity = 3