r"""Find a homomorphism from the Coxeter group :math:`Y_{555}` into the Bimonster


The author has coded a (yet undocumented) implementation of this
homomorphism on his local computer. This will be ported to the 
github repository in a future version.

Warning: The following ducumentation is just as stub!


Description of the task to be done
..................................


The wreath product :math:`\mathbb{M} \wr 2` is of the Monster
:math:`\mathbb{M}` with the group :math:`Z_2` of order 2 is called 
the *Bimonster*. In ATLAS notation :cite:`Atlas` the Bimonster has 
structure :math:`(\mathbb{M} \times \mathbb{M}).2`. It is generated
by :math:`\mathbb{M} \times \mathbb{M}` and an involution
swapping the two copies of  :math:`\mathbb{M}`
 
 

A Coxeter group is a group generated by a finite set 
:math:`s_1,\ldots, s_k` of involutions with a set of relations
:math:`(s_i, s_j)^{\alpha_{i,j}} = 1` for each pair :math:`s_i, s_j`
of involutions. It is called a *hyperbolic reflection group* if
these involutions can be embedded as reflections into a hyperbolic
space. The Coxeter groups discussed in this application  are
given by graphs, where the vertices of the graph correspond to
the generators :math:`s_i`. If two verticges  :math:`s_i, s_j` 
are connected by an edge then we have a relation
:math:`(s_i, s_j)^3 = 1`; otherwise we have a relation 
:math:`(s_i, s_j)^2 = 1`. In the last case the generators
:math:`s_i` and  :math:`s_j` commute. 


Norton and Ivanov have shown that the Bimonster is isomorphic to a
certain hyperbolic reflection group, together with a single 
additional relation, see :cite:`Nor92`, :cite:`Iva92`.
That presentation of the Bimonster is called :math:`Y_{555}`.

The graph corresponding to the Coxeter relations in
:math:`Y_{555}` is given in the followining 
figure 1.


.. tikz:: Warning: This is just an example to check that TikZ works in various environments

   \draw[thick,rounded corners=8pt]
   (0,0)--(0,2)--(1,3.25)--(2,2)--(2,0)--(0,2)--(2,2)--(0,0)--(2,0);




The graph :math:`Y_{555}` can be extended to the incidence 
graph :math:`\mbox{IncP3}` of the projective plane over the 
field :math:`\mathbb{F}_3`. The 26-Node Theorem stated that
there is a homomorphism from the Coxeter group given by
:math:`\mbox{IncP3}` to the Bimonster :math:`\mathbb{M} \wr 2`,
see :cite:`CNS88`. The relations in the generators 
of that Coxeter group defining that homomorphism are well
known; they can  be derived from the Norton-Ivanov theorem,
see e.g. :cite:`Nor02`.





TODO: use :cite:`Far12` and :cite:`Nor02`.



"""

