r"""



The functions in file ``xsp2co1.c`` implement the group operation 
of the subgroup 
:math:`G_{x0}` (of structure :math:`2^{1+24}.\mbox{Co}_1`)
of the monster. 


In :cite:`Seysen20`, section 9.3, the generators  
:math:`x_d, x_\delta, y_\delta, x_\pi, \xi` of :math:`G_{x0}`
are also defined as generators of a group  :math:`G_{x1}` with 
:math:`|G_{x1}:G_{x0}| = 2`. The group :math:`G_{x1}` operates
on a 4096-dimensional rational vector space :math:`4096_x` with 
basis vectors :math:`d_1^+, d_1^-, d \in \mathcal{P}`, and 
relations :math:`(-d)_1^\pm = -d_1^\pm`, 
:math:`(\Omega  d)_1^+ = d_1^+`, 
:math:`(\Omega  d)_1^- = -d_1^-`. The subgroup :math:`G_{x0}` 
of the monster does not operate on the space  :math:`4096_x`. 
But :math:`G_{x0}` operates faithfully on the tensor product  
:math:`4096_x \otimes \Lambda`,  with the operation on the
Leech lattice :math:`\Lambda` as described in section 
:ref:`op-leech-label`.

The operation of :math:`G_{x1}` on  :math:`4096_x` has a kernel 
:math:`K(4096_x)`, which is a central subgroup of :math:`G_{x1}` 
of order 2 generated by :math:`y_\Omega`. The group 
:math:`N(4096_x) = G_{x1}/K(4096_x)` is a subgroup of the real 
Clifford group :math:`\mathcal{C}_{12}` described in section
:ref:`clifford-group-label`; and :math:`4096_x` is isomorphic
to standard representation of :math:`N(4096_x)` is that section.
In that section the basis vectors of the standard representaiton
of the Clifford group :math:`\mathcal{C}_{12}` are numbered from
:math:`0` to :math:`2^{12}-1`.

In section :ref:`parker-loop-label` the elements of the
Parker loop are numbered from :math:`0` to :math:`2^{13}-1`.
For :math:`0 \leq d < 2^{11}` we identify the basis
vectors :math:`d_1^-`and :math:`d_1^+` of  :math:`4096_x`
with the basis vectors  :math:`d` and :math:`d+2^{11}` of
the representation of :math:`\mathcal{C}_{12}`, respectively. 

So we use the functions in file ``qmatrix12.c`` for computing
in :math:`N(4096_x)` and the functions in file ``gen_leech.c``
for computing in the automorphism group :math:`\mbox{Co}_1`
of  :math:`\Lambda`. Together, this gives us the capability
to compute in the subgroup :math:`G_{x0}` of the monster.


"""
