r"""



The functions in file ``xsp2co1.c`` implement the group operation 
of the subgroup 
:math:`G_{x0}` (of structure :math:`2^{1+24}.\mbox{Co}_1`)
of the monster. 


In :cite:`Seysen20`, section 9.3, the generators  
:math:`x_d, x_\delta, y_\delta, x_\pi, \xi` of :math:`G_{x0}`
are also defined as generators of a group  :math:`G_{x1}` with 
:math:`|G_{x1}:G_{x0}| = 2`. The group :math:`G_{x1}` operates
on a 4096-dimensional rational vector space :math:`4096_x` with 
basis vectors :math:`d_1^+, d_1^-, d \in \mathcal{P}`, and 
relations :math:`(-d)_1^\pm = -d_1^\pm`, 
:math:`(\Omega  d)_1^+ = d_1^+`, 
:math:`(\Omega  d)_1^- = -d_1^-`. The subgroup :math:`G_{x0}` 
of the monster does not operate on the space  :math:`4096_x`. 
But :math:`G_{x0}` operates faithfully on the tensor product  
:math:`4096_x \otimes \Lambda`,  with the operation of
:math:`G_{x1}` on the Leech lattice :math:`\Lambda` as 
described in section :ref:`op-leech-label`.

The operation of :math:`G_{x1}` on  :math:`4096_x` has a kernel 
:math:`K(4096_x)`, which is a central subgroup of :math:`G_{x1}` 
of order 2 generated by :math:`y_\Omega`. The group 
:math:`N(4096_x) = G_{x1}/K(4096_x)` is a subgroup of the real 
Clifford group :math:`\mathcal{C}_{12}` described in section
:ref:`clifford-group-label`. The representation :math:`4096_x` 
of :math:`N(4096_x)` extends to the standard representation of 
:math:`\mathcal{C}_{12}` described in that section. There the 
basis vectors of that representation are numbered from 
:math:`0` to :math:`2^{12}-1`.

In section :ref:`parker-loop-label` the elements of the
Parker loop are numbered from :math:`0` to :math:`2^{13}-1`.
For :math:`0 \leq d < 2^{11}` we identify the basis
vectors :math:`d_1^+` and :math:`d_1^-` of  :math:`4096_x`
with the basis vectors  :math:`d` and :math:`d+2^{11}` of
the representation of :math:`\mathcal{C}_{12}`, respectively. 

So we may use the functions in file ``qmatrix12.c`` for computing
in :math:`N(4096_x)` and the functions in file ``gen_leech.c``
for computing in the automorphism group :math:`\mbox{Co}_0`
of  :math:`\Lambda`. Together, this gives us the capability
to compute in the subgroup :math:`G_{x0}` of the monster.
It suffices to compute in the Leech lattice modulo 3.

We represent an element :math:`g` of :math:`G_{x0}` as a pair
:math:`(x_g, v_g)` with  
:math:`x_g \in N(4096_x) \subset \mathcal{C}_{12}`. Here 
:math:`v_g \in \Lambda / 3 \Lambda` is the image of the short
Leech lattice vector 
:math:`v_1 = (0,0,1,-1,0,...,0) \in \Lambda` under :math:`g`.
Here :math:`x_g` determines :math:`g \in G_{x0}` up to sign, 
and it suffices to store the image of one short vector in 
:math:`\Lambda` to determine the sign.

In section :ref:`clifford-group-label` a element of
:math:`\mathcal{C}_{12}` is given as a triple 
:math:`(e,A,Q)` representing a :math:`2^{12} \times 2^{12}` 
matrix :math:`M_g`. Here :math:`e` is a signed integral 
power of two, and :math:`(A,Q)` is a pair of bit matrices with
up to 25 rows and up to 49 colums, where the first 24 columns 
belong to matrix :math:`A`, and the remaining columns belong 
to  matrix :math:`Q`.

Changing the sign of :math:`e` corresponds to negation
of a matrix or to  multiplication by :math:`x_{-1}`. Changing 
the sign of :math:`v_1` has the same effect as changing the 
sign of :math:`e`; so  :math:`e` can always be made positive. 
The absolute value of :math:`e` is just there for scaling the 
operator norm to 1, and can be omitted..

Assuming a positive scalar factor :math:`e`, we can represent 
a matrix :math:`M_g` corresponding to an 
:math:`x_g \in N(4096_x)` as a pair :math:`(A,Q)` as above. 
Vector :math:`v_g \in \Lambda / 3 \Lambda` is represented as 
a 48-bit integer.
 
Internally, we represent a pair :math:`(x_g, v_g)` as an array
of 1+25 integers of type ``uint64_t``, where the first entry 
represents :math:`v_g`, and the remaining 25 entries 
represent :math:`x_g` as a pair :math:`(A,Q)` of bit matrices,
with zero rows and columns appended if necessary. 
We always store the pair  :math:`(A,Q)` in reduced form, as 
indicated in :ref:`clifford-group-label`, so that the 
representation of a :math:`g \in G_{x0}` in memory is unique.
 

TODO: explain basis transformation in :math:`4096_x` for conjugation
of :math:`x_d, x_\delta`!!!





"""
