r"""
In this section we briefly describe the mathematical tools used
for the mapping from the Coxeter group :math:`\mbox{IncP3}` to the 
Bimonster.

Therefore we use the Norton's presentation :cite:`Nor02` of the 
Monster. Then we follow the ideas in Farooq's thesis :cite:`Far12` 
for extending that presentation of the Monster to a homomorphism from 
the Coxeter group :math:`\mbox{IncP3}` to the Bimonster.
We assume that the reader is familiar with :cite:`Nor02` and 
we will adopt notation from ibid.


Norton's presentation of the Monster and the Bimonster
.......................................................

Let :math:`\mbox{IncP3}` be the Coxeter group generated by the 
nodes of the projective plane :math:`\mbox{P3}` as above, and let
:math:`\mbox{AutP3}` be the automorphism group of :math:`\mbox{P3}`.
Let :math:`\,\mbox{IncP3}:\mbox{AutP3}\,` be the extension group 
where :math:`\mbox{AutP3}`  acts naturally on the generating
reflections of the Coxeter group :math:`\mbox{IncP3}`.

Norton :cite:`Nor02` defines a presentation :math:`(s,t,u,v,x,\alpha)`
of the group :math:`\mbox{IncP3}:\mbox{AutP3}`, where 
:math:`s,t,u \in \mbox{AutP3}`, :math:`v = \prod_{i=1}^{12} P_i`,  
:math:`x = P_0 L_0`, :math:`\alpha = P_0 v`. 
Then he adds a relation that maps :math:`\mbox{IncP3}` to the 
Bimonster :math:`\mathbb{M} \wr 2`, thus obtaining a presentation of
:math:`(\mathbb{M} \wr 2):\mbox{AutP3}`. Next he shows that
this is actually a presentation of the direct product 
:math:`(\mathbb{M} \wr 2) \times \mbox{AutP3}`. Then he adds a
set of relations that cancel the factor :math:`\mbox{AutP3}`, 
leading to a presentation of the Bimonster with the generators
:math:`(s,t,u,v,x,\alpha)`. It turns out that all these generators,
except for :math:`\alpha`, are in the subgroup
:math:`\mathbb{M} \times \mathbb{M}` of index 2 of the Bimonster
:math:`\mathbb{M} \wr 2`. Finally, he gives a further set of 
relations in the generators :math:`(s,t,u,v,x)` cancelling the second 
factor of the direct product :math:`\mathbb{M} \times \mathbb{M}`,
thus obtaining a presentation of the Monster :math:`\mathbb{M}`.

Mapping Norton's presentation into the Monster
..............................................

Essentially, our task is to construct an explicit mapping from the
generators :math:`(s,t,u,v,x,\alpha)` into :math:`\mathbb{M} \wr 2`.
A first step for achieving this is to construct a mapping 
:math:`\phi` from
the generators :math:`(s,t,u,v,x)` to :math:`\mathbb{M}`.


In :cite:`Nor02` for each point :math:`P_i` an element :math:`P^*_i`
of of the subgroup :math:`\mathbb{M} \times \mathbb{M}` of the
Bimonster is defined. The elements :math:`P^*_i` are called the 
*stars* (corresponding to the points :math:`P_i`), and it is shown 
that :math:`\mbox{AutP3}` permutes the stars :math:`P^*_i` in the 
same  way as it permutes the corresponding points.
Note that only products of an even number of points are in
the subgroup :math:`\mathbb{M} \times \mathbb{M}` of
:math:`\mathbb{M} \wr 2`.  


According to :cite:`Nor02` we have :math:`\phi(x) = \tau` for the 
generator :math:`x`, where :math:`\tau` is  the triality element of the 
Monster. There it is also shown that the stars and the 
(products of an even number of) points map to elements of the 
extraspecial subgroup  :math:`Q_{x0}` (of structure :math:`2^{1+24}`) 
of the Monster. In :cite:`Nor02` explicit images of the points and 
stars in :math:`Q_{x0}` are constructed up to sign. More specifically,
the images of these elements are given in the Leech lattice modulo 2,
which is isomorphic to the quotient of :math:`Q_{x0}` by its centre
:math:`\{1, x_{-1}\}`.
It is easy to see that the signs of the images of the points and
stars may be chosen arbitrarily, with the only restriction that
the product :math:`P^*_0 P^*_1 P^*_3 P^*_9` must be mapped to
the element :math:`x_{\Omega}` of :math:`Q_{x0}` and not to its
negative :math:`x_{-\Omega}`. It can be shown that the tuple
:math:`(P_0 P_1, \ldots, P_0 P_{12}, P^*_1,  \ldots, P^*_{12})`,
when taken modulo the centre of :math:`Q_{x0}`, corresponds to a 
basis of the Leech lattice modulo 2. So for defining the mapping 
:math:`\phi` on the points and the stars it suffices to specify
the signs of the images of the entries of that tuple. It turns out
that everything works fine if we declare all these singn to be
positive. This means that for any such  image :math:`x_d x_\delta`,
:math:`d \in \mathcal{P}, \delta \in C^*`, we choose :math:`d` to
be a 'positive' element of the Parker loop :math:`\mathcal{P}`,
according to our construction of :math:`\mathcal{P}`.
  
With this choice the mapping :math:`\phi` is uniquely defined
on the points and on the stars; and we shall see that it is
also uniquely defined on all generators :math:`(s,t,u,v,x)` 
of the presentation given in :cite:`Nor02`. The functions
``PointP3`` and ``StarP3`` in module 
``mmgroup.bimm.p3_to_mm`` compute the mapping :math:`\phi` on
the points and the stars, respectively.

Mapping :math:`\phi` is already defined on  :math:`x` and on
:math:`v` (since :math:`v` is a product of points). Generators
:math:`s,t,u,` are defined as automorphisms in :math:`\mbox{AutP3}`,
so it suffices compute :math:`\phi(a)` for :math:`a \in \mbox{AutP3}`.


It is also shown in :cite:`Nor02` that the images of elements of
:math:`\mbox{AutP3}` are in the centralizer  :math:`G_{x0}` 
(of structure :math:`2^{1+24}.\mbox{Co}_1`) of the element
:math:`x_{-1}`. Note that the images of the points and the stars
generate the group :math:`Q_{x0}`; so the action of any automorphism
in :math:`\mbox{AutP3}` is determined (as an element of 
:math:`G_{x0}`) by its action on the points and the stars, up to 
sign. The group :math:`\mbox{AutP3}` is the simple group 
:math:`L_3(3)` in ATLAS notation. Thus it is generated by its
elements of odd order. For any :math:`g \in G_{x0}` at most one
of the elements  :math:`g, x_{-1} \cdot g` has odd order, so that 
the correct image of any element of :math:`\mbox{AutP3}` of  odd
order (and hence the image of the any element of
:math:`\mbox{AutP3}`) in :math:`G_{x0}` is uniquely defined.
So we can also construct the images of the generators
:math:`(s,t,u)`. Function ``Norton_generators`` in module
``mmgroup.bimm.p3_to_mm`` returns the images of the generators
:math:`(s,t,u,v,x)` under our mapping :math:`\phi`.

Faaroq :cite:`Far12` had to perform strenuous calculations for
actually computing :math:`\phi` on :math:`\mbox{AutP3}`, since he 
had to use the representations of the groups :math:`G_{x0}` and
:math:`\mathbb{M}` available in 2012. With or construction of the
Monster and of :math:`G_{x0}` we are in a much more comfortable
situation. Function ``AutP3_MM`` in module ``mmgroup.bimm.p3_to_mm``
quickly computes the mapping :math:`\phi` on :math:`\mbox{AutP3}`. 
In the remainder of this subsection we discuss the operation of 
that function.

The relevant automorphsims :math:`a \in \mbox{AutP3}` are given as
mappings between the 13 points and the 13 stars, where the stars 
are  transformed in the same way as corresponding points. Using our 
contruction of :math:`\phi` on the points and the stars, the image 
:math:`\phi(a)`  can be given as an automorphism of  :math:`Q_{x0}` 
in  :math:`G_{x0}`,
where :math:`G_{x0}` operates on :math:`Q_{x0}` by conjugation.
Given such an automorphism on :math:`Q_{x0}`, the C function
``xsp2co1_elem_from_mapping`` in file ``xsp2co1_map.c`` computes 
the corresponding element of the group :math:`G_{x0}` (up to sign).


TODO: Explain math behind function ``xsp2co1_elem_from_mapping``!!!
"""

